/**
 * Custom worker entry that combines OpenNext worker with ChatAgent Durable Object
 *
 * This file is referenced in wrangler.toml as the main entry point instead of
 * the default .open-next/worker.js, allowing us to export both the Next.js app
 * and the ChatAgent Durable Object.
 */

// @ts-expect-error - .open-next/worker.js is generated by OpenNext build
export { default } from './.open-next/worker.js';

// Re-export ChatAgent Durable Object class
export { ChatAgent } from './src/agent';
