/**
 * Worker entry point for OpenNext Cloudflare deployment
 *
 * Simply re-exports the OpenNext worker. The ChatAgent Durable Object
 * has been removed from this deployment to reduce bundle size.
 *
 * The web app uses direct AI SDK calls via the /api/chat route instead
 * of the full ChatAgent framework.
 */

// @ts-expect-error - .open-next/worker.js is generated by OpenNext build
export { default } from './.open-next/worker.js';
