packages:
  - 'packages/*'
  - 'apps/*'
  - 'tests/*'

catalog:
  '@modelcontextprotocol/sdk': 1.24.2
  '@types/node': 22.10.0
  '@types/react': 19.0.0
  agents: 0.3.0
  hono: 4.11.2
  typescript: 5.7.2
  vitest: 4.0.16
  wrangler: 4.50.0
  zod: 3.23.8
  zod-to-json-schema: 3.24.5
