# pnpm workspace configuration for duyetbot-agent monorepo
packages:
  # Core packages
  - 'packages/*'

  # Applications
  - 'apps/*'

# Shared dependency catalog - ensures version consistency across packages
catalog:
  # Runtime dependencies
  '@anthropic-ai/claude-agent-sdk': ^0.1.49
  '@anthropic-ai/sdk': ^0.70.1
  'zod': ^3.23.8
  'hono': ^4.10.6
  'jose': ^6.1.2
  'chalk': ^5.6.2
  'commander': ^14.0.2
  'ora': ^9.0.0

  # React ecosystem
  'react': ^19.0.0
  'ink': ^6.5.0
  '@types/react': ^19.0.0

  # Development dependencies
  'typescript': ^5.7.2
  'vitest': ^2.1.8
  '@types/node': ^22.10.0
  'tsx': ^4.20.6

  # Cloudflare
  '@cloudflare/workers-types': ^4.20251121.0
  '@cloudflare/vitest-pool-workers': ^0.10.10
  'wrangler': ^3.94.0

  # Build tools
  '@biomejs/biome': ^1.9.4
  'turbo': ^2.0.0
