// @ts-nocheck
import * as __fd_glob_60 from "../../../docs/guides/webhook.md?collection=docs"
import * as __fd_glob_59 from "../../../docs/guides/telegram-bot.md?collection=docs"
import * as __fd_glob_58 from "../../../docs/guides/telegram-bot-setup.md?collection=docs"
import * as __fd_glob_57 from "../../../docs/guides/slack-setup.md?collection=docs"
import * as __fd_glob_56 from "../../../docs/guides/github-bot.md?collection=docs"
import * as __fd_glob_55 from "../../../docs/guides/github-bot-setup.md?collection=docs"
import * as __fd_glob_54 from "../../../docs/guides/env-setup.md?collection=docs"
import * as __fd_glob_53 from "../../../docs/guides/deployment.md?collection=docs"
import * as __fd_glob_52 from "../../../docs/guides/deploy.md?collection=docs"
import * as __fd_glob_51 from "../../../docs/guides/custom-tools.md?collection=docs"
import * as __fd_glob_50 from "../../../docs/guides/custom-do.md?collection=docs"
import * as __fd_glob_49 from "../../../docs/guides/cloudflare-first.md?collection=docs"
import * as __fd_glob_48 from "../../../docs/guides/cloudflare-deploy.md?collection=docs"
import * as __fd_glob_47 from "../../../docs/guides/build-custom-agent.md?collection=docs"
import * as __fd_glob_46 from "../../../docs/guides/agent-server.md?collection=docs"
import * as __fd_glob_45 from "../../../docs/reference/tables.md?collection=docs"
import * as __fd_glob_44 from "../../../docs/reference/schemas.md?collection=docs"
import * as __fd_glob_43 from "../../../docs/reference/router-cheatsheet.md?collection=docs"
import * as __fd_glob_42 from "../../../docs/reference/rate-limiting.md?collection=docs"
import * as __fd_glob_41 from "../../../docs/reference/query.md?collection=docs"
import * as __fd_glob_40 from "../../../docs/reference/hooks.md?collection=docs"
import * as __fd_glob_39 from "../../../docs/reference/hono-middleware.md?collection=docs"
import * as __fd_glob_38 from "../../../docs/reference/health.md?collection=docs"
import * as __fd_glob_37 from "../../../docs/reference/auth-middleware.md?collection=docs"
import * as __fd_glob_36 from "../../../docs/reference/api.md?collection=docs"
import * as __fd_glob_35 from "../../../docs/concepts/transports.md?collection=docs"
import * as __fd_glob_34 from "../../../docs/concepts/tools.md?collection=docs"
import * as __fd_glob_33 from "../../../docs/concepts/subagent.md?collection=docs"
import * as __fd_glob_32 from "../../../docs/concepts/simple-agent.md?collection=docs"
import * as __fd_glob_31 from "../../../docs/concepts/router-agent.md?collection=docs"
import * as __fd_glob_30 from "../../../docs/concepts/orchestrator-agent.md?collection=docs"
import * as __fd_glob_29 from "../../../docs/concepts/memory-mcp.md?collection=docs"
import * as __fd_glob_28 from "../../../docs/concepts/hitl-integration.md?collection=docs"
import * as __fd_glob_27 from "../../../docs/concepts/durable-objects.md?collection=docs"
import * as __fd_glob_26 from "../../../docs/concepts/do-patterns.md?collection=docs"
import * as __fd_glob_25 from "../../../docs/concepts/do-limits.md?collection=docs"
import * as __fd_glob_24 from "../../../docs/concepts/batching-strategies.md?collection=docs"
import * as __fd_glob_23 from "../../../docs/concepts/batching-alarms.md?collection=docs"
import * as __fd_glob_22 from "../../../docs/concepts/batch-routing.md?collection=docs"
import * as __fd_glob_21 from "../../../docs/community/troubleshooting.md?collection=docs"
import * as __fd_glob_20 from "../../../docs/community/readme-multiagent.md?collection=docs"
import * as __fd_glob_19 from "../../../docs/community/fork-pr.md?collection=docs"
import * as __fd_glob_18 from "../../../docs/community/feedback.md?collection=docs"
import * as __fd_glob_17 from "../../../docs/community/faqs.md?collection=docs"
import * as __fd_glob_16 from "../../../docs/community/contributing.md?collection=docs"
import * as __fd_glob_15 from "../../../docs/community/checklists.md?collection=docs"
import * as __fd_glob_14 from "../../../docs/advanced/use-cases.md?collection=docs"
import * as __fd_glob_13 from "../../../docs/advanced/token-optimization.md?collection=docs"
import * as __fd_glob_12 from "../../../docs/advanced/token-optimization-guide.md?collection=docs"
import * as __fd_glob_11 from "../../../docs/advanced/flow-diagrams.md?collection=docs"
import * as __fd_glob_10 from "../../../docs/advanced/cloudflare-agents.md?collection=docs"
import * as __fd_glob_9 from "../../../docs/advanced/benchmarks.md?collection=docs"
import * as __fd_glob_8 from "../../../docs/index.md?collection=docs"
import * as __fd_glob_7 from "../../../docs/getting-started.md?collection=docs"
import * as __fd_glob_6 from "../../../docs/architecture.md?collection=docs"
import * as __fd_glob_5 from "../../../docs/README.md?collection=docs"
import { default as __fd_glob_4 } from "../../../docs/guides/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../../../docs/reference/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../../../docs/concepts/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../../../docs/community/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../../../docs/advanced/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "../../docs", {"advanced/meta.json": __fd_glob_0, "community/meta.json": __fd_glob_1, "concepts/meta.json": __fd_glob_2, "reference/meta.json": __fd_glob_3, "guides/meta.json": __fd_glob_4, }, {"README.md": __fd_glob_5, "architecture.md": __fd_glob_6, "getting-started.md": __fd_glob_7, "index.md": __fd_glob_8, "advanced/benchmarks.md": __fd_glob_9, "advanced/cloudflare-agents.md": __fd_glob_10, "advanced/flow-diagrams.md": __fd_glob_11, "advanced/token-optimization-guide.md": __fd_glob_12, "advanced/token-optimization.md": __fd_glob_13, "advanced/use-cases.md": __fd_glob_14, "community/checklists.md": __fd_glob_15, "community/contributing.md": __fd_glob_16, "community/faqs.md": __fd_glob_17, "community/feedback.md": __fd_glob_18, "community/fork-pr.md": __fd_glob_19, "community/readme-multiagent.md": __fd_glob_20, "community/troubleshooting.md": __fd_glob_21, "concepts/batch-routing.md": __fd_glob_22, "concepts/batching-alarms.md": __fd_glob_23, "concepts/batching-strategies.md": __fd_glob_24, "concepts/do-limits.md": __fd_glob_25, "concepts/do-patterns.md": __fd_glob_26, "concepts/durable-objects.md": __fd_glob_27, "concepts/hitl-integration.md": __fd_glob_28, "concepts/memory-mcp.md": __fd_glob_29, "concepts/orchestrator-agent.md": __fd_glob_30, "concepts/router-agent.md": __fd_glob_31, "concepts/simple-agent.md": __fd_glob_32, "concepts/subagent.md": __fd_glob_33, "concepts/tools.md": __fd_glob_34, "concepts/transports.md": __fd_glob_35, "reference/api.md": __fd_glob_36, "reference/auth-middleware.md": __fd_glob_37, "reference/health.md": __fd_glob_38, "reference/hono-middleware.md": __fd_glob_39, "reference/hooks.md": __fd_glob_40, "reference/query.md": __fd_glob_41, "reference/rate-limiting.md": __fd_glob_42, "reference/router-cheatsheet.md": __fd_glob_43, "reference/schemas.md": __fd_glob_44, "reference/tables.md": __fd_glob_45, "guides/agent-server.md": __fd_glob_46, "guides/build-custom-agent.md": __fd_glob_47, "guides/cloudflare-deploy.md": __fd_glob_48, "guides/cloudflare-first.md": __fd_glob_49, "guides/custom-do.md": __fd_glob_50, "guides/custom-tools.md": __fd_glob_51, "guides/deploy.md": __fd_glob_52, "guides/deployment.md": __fd_glob_53, "guides/env-setup.md": __fd_glob_54, "guides/github-bot-setup.md": __fd_glob_55, "guides/github-bot.md": __fd_glob_56, "guides/slack-setup.md": __fd_glob_57, "guides/telegram-bot-setup.md": __fd_glob_58, "guides/telegram-bot.md": __fd_glob_59, "guides/webhook.md": __fd_glob_60, });